spring:
  datasource:
    url: jdbc:h2:mem:trending_recipes_db
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: trending-recipes

